def ImportPETSc(arch=None): ...
def getPathArchPETSc(arch=None): ...
def Import(pkg, name, path, arch): ...
def getPathArch(path, arch, rcvar: str = 'PETSC_ARCH', rcfile: str = 'petsc.cfg'): ...
def getInitArgs(args): ...
